#将静态内容部署到GUUUB页面的简单工作流


 在…上  :
  #开始以默认分支为目标
  推动   :
    分枝           : [           "main"           ]

  #允许您从操作选项卡手动运行此工作流
  工作流程           :

#设置了使部署得以实现JUTUB页面的JUTUB_托肯权限
准许           :
  目录         :            内容 : 改为
  页        :           页 : 书写
  令人印象深刻的       :          印 : 写

#只允许一个并发部署,在正在进行的运行和最新的队列之间跳过排队的运行。
#但是,不要取消正在进行的运行,因为我们希望允许这些生产部署完成。
并发的     :
  团体    : "pages"
  正在取消的   : 假的

乔布斯 :
  #单一部署任务因为我们刚刚部署
  部署  :
    环境   :
      姓名:吉特布-帕奇
      : $ {     { steps.deployment.outputs.page_url }    }
    最新运行   :
    步骤  :
      名称:结账
        用途:行动/结账@V4
      -名称:设置页
        用途:操作/配置页@V5
      -名称:上载艺术品

        与…有关  :
          #上提载及输入库#上载整个储存库
          通道      : '.'
      - 姓名     :            -名称 : 部署到千分通页
        身份证    :             说明 : 部署
        使用   :            用途:行动/部署页@V4
